ai_goals:
- 'foundations legal insurance '
- marketing
- training tips
- safety
- walks
ai_name: Dog walkers ebook
ai_role: write an ebook for people wishing to start a dog walking business in the
  UK including up to date training tips
